CREATE TABLE Provinsis (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  location POINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  SPATIAL INDEX(location)  -- Menambahkan index spatial
);

CREATE TABLE Kota (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  location POINT NOT NULL,
  provinsi_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (provinsi_id) REFERENCES Provinsis(id),
  SPATIAL INDEX(location)  -- Menambahkan index spatial
);

CREATE TABLE AmbulanceProviders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone_number VARCHAR(255) NOT NULL,
  ambulance_provider_name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  location POINT NOT NULL,
  kota_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (kota_id) REFERENCES Kota(id),
  SPATIAL INDEX(location)  -- Menambahkan index spatial
);

CREATE TABLE Hospitals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hospital_name VARCHAR(255),
  phone_number VARCHAR(255),
  kelas ENUM('A', 'B', 'C', 'D', 'E') NOT NULL,
  location POINT NOT NULL,
  kota_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (kota_id) REFERENCES Kota(id),
  SPATIAL INDEX(location)  -- Menambahkan index spatial
);

CREATE TABLE EmergencyEvents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  user_location POINT NOT NULL,
  driver_id INT DEFAULT NULL,
  ambulance_provider_id INT DEFAULT NULL,
  hospital_id INT DEFAULT NULL,
  emergency_type ENUM('MERAH', 'KUNING', 'HIJAU', 'PUTIH', 'HITAM'),
  number_of_patient INT DEFAULT 1,
  title VARCHAR(255),
  descriptions VARCHAR(255),
  is_done BOOLEAN DEFAULT FALSE,
  is_canceled BOOLEAN DEFAULT FALSE,
  rating ENUM('1', '2', '3', '4', '5') DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES UserAccounts(id),
  FOREIGN KEY (driver_id) REFERENCES DriverAccounts(id),
  FOREIGN KEY (ambulance_provider_id) REFERENCES AmbulanceProviders(id),
  FOREIGN KEY (hospital_id) REFERENCES Hospitals(id),
  SPATIAL INDEX(user_location)  -- Menambahkan index spatial
);

CREATE TABLE AdminAccounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE UserOTPs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phoneNumber VARCHAR(255) NOT NULL,
  otp VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
